name: training-log-pro-test-stack
services:

  traefik:
    image: traefik:v3.6
    ports:
      - "8180:80"
      - "8181:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./test/traefik.yaml:/etc/traefik/traefik.yaml:ro
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 2s
      retries: 5
      start_period: 2s

  client:
    build:
      context: client
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.routers.client.priority=1"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    healthcheck:
      test: "wget --quiet --tries=1 --spider http://localhost/ || exit 1"
      interval: 2s
      retries: 10
      start_period: 5s
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: server
    user: "${USER_ID}:${GROUP_ID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.server.priority=2"
      - "traefik.http.services.server.loadbalancer.server.port=8080"
    environment:
      SPRING_ACTUATOR_PORT: "8182"
      SPRING_PROFILES_ACTIVE: "test"
      DB_URL: "jdbc:postgresql://db:5432/test"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
    healthcheck:
      test: "curl --fail --silent localhost:8182/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      retries: 10
      start_period: 16s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:17.5-bullseye"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5460:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
