spring:
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS training_log; SET search_path TO training_log, public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        jdbc:
          time-zone: UTC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: training_log
    liquibase-schema: training_log
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${AZURE_KEYVAULT_ENDPOINT}
              enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${tenant-id:}/v2.0
          audiences: ${api-client-id:}
      client:
        provider:
          withings:
            authorization-uri: https://account.withings.com/oauth2_user/authorize2
            token-uri: https://wbsapi.withings.net/v2/oauth2
          strava:
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
        registration:
          withings-client:
            provider: withings
            client-id: ${withings-client-id}
            client-secret: ${withings-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/withings/authorize"
            scope: user.metrics
          strava-client:
            provider: strava
            client-id: ${strava-client-id}
            client-secret: ${strava-client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/strava/authorize"
            scope: activity:read
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api
management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
withings:
  api-uri: https://wbsapi.withings.net
strava:
  username: ${strava-username}
  password: ${strava-password}
  api-uri: https://www.strava.com
playwright:
  ws-endpoint: ${playwright-server-url}
