spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/training_log
    username: postgres
    password: postgres
  cloud:
    azure:
      active-directory:
        credential:
          client-secret: ${api-client-secret}
management:
  server:
    port: 8182
