spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - enabled: false
  security:
    oauth2:
      client:
        provider:
          withings:
            authorization-uri: http://localhost:3080/withings/oauth2_user/authorize2
            token-uri: http://localhost:3080/withings/v2/oauth2
          strava:
            authorization-uri: http://localhost:3081/strava/oauth/authorize
            token-uri: http://localhost:3081/strava/oauth/token
        registration:
          withings-client:
            client-id: withings-client-id
            client-secret: withings-client-secret
          strava-client:
            client-id: strava-client-id
            client-secret: strava-client-secret
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/default
          audiences: mock-api-client-id
mock-oauth2-server-uri: ${MOCK_OAUTH2_SERVER_URI:}
withings:
  api-uri: http://localhost:3080/withings
strava:
  username: "rob"
  password: "123"
  api-uri: http://localhost:3081/strava
playwright:
  ws-endpoint: ${PLAYWRIGHT_WS_ENDPOINT:}
management:
  server:
    port: ${server.port:0}
