spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5435/training_log
    username: postgres
    password: postgres
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - enabled: false
      active-directory:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

management:
  server:
    port: ${server.port:0}
