apiVersion: v1
kind: Pod
metadata:
  name: training-log-pro-dev
spec:
  containers:
    - name: db
      image: docker.io/library/postgres:17.5-bullseye
      ports:
        - containerPort: 5432
          hostPort: 5482
      env:
        - name: POSTGRES_DB
          value: training_log
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      livenessProbe:
        exec:
          command: ["pg_isready", "-U", "postgres"]
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 5
  volumes:
    - name: postgres-data
      hostPath:
        path: postgres-data
        type: DirectoryOrCreate
